language: python
python:
  - 3.3
  - 3.4
branches:
  only:
    - master
    - develop
notifications:
  email: false

sudo: false

before_install:
  - bash continuous-integration/travis/install.sh

# Install packages
install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-environment
  - which python
  - conda list

# Run test
script:
  - "coverage run --source=acousticsim setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/tools
